name: Deploy Frontend to Vercel

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Pull Vercel env (Preview)
        if: github.event_name == 'pull_request' || github.ref != 'refs/heads/master'
        run: npx vercel pull --yes --environment=preview --project-id ${{ secrets.VERCEL_PROJECT_ID }} --org-id ${{ secrets.VERCEL_ORG_ID }} --token ${{ secrets.VERCEL_TOKEN }}

      - name: Pull Vercel env (Production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx vercel pull --yes --environment=production --project-id ${{ secrets.VERCEL_PROJECT_ID }} --org-id ${{ secrets.VERCEL_ORG_ID }} --token ${{ secrets.VERCEL_TOKEN }}

      - name: Build (Vercel)
        run: npx vercel build --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy (Preview)
        if: github.event_name == 'pull_request' || github.ref != 'refs/heads/master'
        run: npx vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }} --project-id ${{ secrets.VERCEL_PROJECT_ID }} --org-id ${{ secrets.VERCEL_ORG_ID }}

      - name: Deploy (Production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }} --project-id ${{ secrets.VERCEL_PROJECT_ID }} --org-id ${{ secrets.VERCEL_ORG_ID }}
